spring.application.name=franchise-api
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb+srv://jcleon892_db_user:DrMRLdoYAgEpW3XU@cluster0.lsvnmvi.mongodb.net/franchise-api?retryWrites=true&w=majority}
